### PR TITLE
Add timezone role

### PR DESCRIPTION
**Pull request by tersmitten**
This way we can cleanup some inline tasks in several `Freyfiles`

### CODE REVIEW

**Comment by kvz** [comment]
Good stuff! Can you please also add an entry to `CHANGELOG.md` as part of this PR?

**Comment by tersmitten** [comment]
Sure

**Comment by tersmitten** [comment]
Do you want me to update the changelog every pull request?

**Comment by kvz** [comment]
Yes that would be great 👌 Currently I'm updated the changelog myself but it's harder to keep track that way, so I think they feature changes / bugfixes might as well carry themselves into the CHANGELOG 👍

**Comment by tersmitten** [comment]
Will do!

**Comment by tersmitten** [comment]
Done

**Pull request merged**
