### PR TITLE
Adjust getroles.sh to use Github

### PR DESCRIPTION
**Pull request by tersmitten**

### CODE REVIEW

**Comment by tersmitten** [comment]
@kvz Let's have a chat soon. You can already have a look at `getroles.sh`, but I especially need some input on the tagging and maintain of the (forked) roles. Also how you want to handle the differences that are present now.

**Comment by kvz** [comment]
Sounds good, Thu?

(since this is marked WIP I'm not reviewing this yet)

**Comment by tersmitten** [comment]
Tomorrow is fine, let's pick a time in slack.

**Comment by tersmitten** [comment]
This is done as far as I'm concerned. All roles are properly tagged and all Frey specific changes (re)applied.

The `getroles.sh` script downloads to `roles/1.0.0` now, so no more `roles/v1.0.0`. All exiting download are still intact.

Once we merge this we can upgrade all Frey projects to use the new downloads (without `v`). This should require no configuration changes (except for removing the `v` in the `Freyfile`), because all Frey specific changes were (re)applied. The `apt` role is an exception since it's a new one (I'll make an example upgrade in the `frey` repository). The `rsyslog` role is also an exception since it's first Frey version is `3.1.0` while you are probably still using `3.0.1` or `3.0.2`. Upgrading should be no problem since `3.1.0` is fully backwards compatible.

Let's have a chat soon. Maybe tomorrow if you have time?

**Comment by kvz** [comment]
Sounds good! Merging this already. 

Bit busy today, perhaps in the afternoon?

**Comment by tersmitten** [comment]
This afternoon is fine. I'm available till 16:30.

**Pull request merged**
